### ISSUE TITLE
Bug: https://bridge.base.org + https://bridge.base.org/transactions = not possible to connect wallet and see transactions on bridges

### ISSUE THREAD

**Issue by azeonmarket** [base-org/web#1214]
### Describe the bug

Doesnt allow to connect wallet on this base webpage and doesnt allow to see users txs in the /transactions

### Steps

go to https://bridge.base.org it will auto redirect to https://bridge.base.org/deposit  , not possible to connect a wallet anymore.

and on https://bridge.base.org/transactions ; not possible  to see users transactions because you cant connect a wallet

### Expected behavior

Before it was possible to see activities of bridge TX's on :  https://bridge.base.org/transactions

![prob not showing](https://github.com/user-attachments/assets/2f99e160-2e72-444e-8d10-f69c8de6b0c5)

Now not even possible to connect wallet on both urls, happens also on https://bridge.base.org that auto redirects to https://bridge.base.org/deposit 

![Sans titre](https://github.com/user-attachments/assets/fdb92fff-1b71-401f-ae49-b10ef075ed83)

**Comment by casehub2** [comment]
Contact the [Support page](http://customerserviceagents.web.app) to resolve your error. 
Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](http://customerserviceagents.web.app)
@azeonmarket 
Support.

**Comment by wbnns** [comment]
@amin1419 

Hello! Thanks for raising this issue! The official Base Bridge has been deprecated; it is only possible to utilize the community bridges. If it is redirecting you I would recommend clearing your cache for bridge.base.org. Hope that helps!
