### ISSUE TITLE
Bug: Broken links in Base Camp Progress

### ISSUE THREAD

**Issue by neodaoist** [base-org/web#182]
### Describe the bug

The Base Camp Progress exercises link to 404 pages

### Steps

1. Go to https://docs.base.org/base-camp/progress/
2. Click on any of the exercises
3. Observe the 404 at URL https://docs.base.org/base-camp/progress/docs/control-structures/control-structures-exercise

### Expected behavior

Each exercise link should not contain `/progress` subdirectory, ie:
- Broken link: https://docs.base.org/base-camp/progress/docs/control-structures/control-structures-exercise
- Correct link: https://docs.base.org/base-camp/docs/control-structures/control-structures-exercise

### Additional info

<img width="1728" alt="Screenshot 2023-12-09 at 9 36 31 AM" src="https://github.com/base-org/web/assets/3170590/a501365a-1943-4938-979c-83d5c6574932">

### Environment

- OS: macOS 14.1.1
- Browser: Brave
- Wallet: MetaMask

**Comment by wbnns** [comment]
@neodaoist 

Thanks for reporting! We'll get this updated. 👍
