### ISSUE TITLE
Bug: Invalid links for 3 Base apps

### ISSUE THREAD

**Issue by clintmoyer** [base-org/web#215]
### Describe the bug

The following Base applications from the Ecosystem page do not load: Seamless, Showtime, Base Treasure Hunt

### Steps

1. Go to https://base.org/ecosystem
2. Search for application by name
3. Click link

### Expected behavior

The links should take the user to the respective Base application.

**Comment by wbnns** [comment]
@clintmoyer Thanks a bunch for reporting! We'll get this fixed!
