### ISSUE TITLE
Support for Sepolia testnet in the toolchains guide

### ISSUE THREAD

**Issue by mx644** [base-org/web#219]
We need to introduce support for the Sepolia testnet in our documentation. As Sepolia is now recommended for smart contract development, and with Goerli having been deprecated in Q1 2023 with support ending in Q4 2023, it's important we make this update where Goerli occurs.

I've updated the [toolchains guide for Hardhat](https://docs.base.org/tools/hardhat/) and submitted a [PR](https://github.com/base-org/web/pull/218) to include the Sepolia network settings with the appropriate endpoints on base, but I'll take a look at other parts of the documentation (the Foundry section could be a bit more robust).

It's probably a smart idea to retain Goerli for the time being too, with the plan of phasing its documentation out gradually.

**Comment by wbnns** [comment]
@hoffeig 

Thanks! We'll review the PR you opened for this soon. 👍
