### ISSUE TITLE
Docs Request: Create Contract to Contract Interactions Exercise/Videos and Move to Smart Contract Development Section

### ISSUE THREAD

**Issue by anader123** [base-org/web#236]
### What is the issue you are encountering with the docs?

Contract to Contract Interactions is currently housed in the hardhat section. This feels like a critical section that should be moved to the smart contract development section and given an exercise/video explanations.

### Links to Impacted Docs

https://docs.base.org/base-camp/docs/interfaces/contract-to-contract-interaction

### Describe the solution you'd like to see.

Create a Contract to Contract Interaction exercise and move it to the smart contract development section.

**Comment by briandoyle81CB** [comment]
Thanks for the suggestions!  Moved the content, and have a new issue for creating an exercise.

We're not producing new video at the moment, while we evaluate the value vs. cost of producing and updating them in such a rapidly evolving environment.
