### ISSUE TITLE
[Onchain Squad] Create a new developer guide around building on Base

### ISSUE THREAD

**Issue by taycaldwell** [base-org/web#251]
### Context

We're continually adding new developer guides and tutorials to the Base Developer Docs for developers to learn new concepts and tooling when building on Base.

### Ask

Write a new guide around building onchain apps (dapps) on Base using your favorite tooling, or take one of the existing guides and  improve the existing content to make it more digestible and easier to learn!

_Source code for the Base Developer Docs site can be found under [/apps/base-docs](https://github.com/base-org/web/tree/master/apps/base-docs). The documentation site is built using [Docusaurus](https://docusaurus.io/)._

**Comment by bobeu** [comment]
@taycaldwell Could you assign this to me if it is open?

**Comment by bobeu** [comment]
Thank you @taycaldwell I will get to it as soon as possible.

**Comment by taycaldwell** [comment]
Closing issue with conclusion of 30 Days of Web3.
