### ISSUE TITLE
[Onchain Squad] Add missing tooling and / or libraries

### ISSUE THREAD

**Issue by taycaldwell** [base-org/web#253]
### Context

Developers can use a variety of different tooling and libraries when building their onchain apps on Base. Although we try to list and cover as many as we can within our Developer Docs, we might have missed some along the way!

### Ask

Identify popular developer tooling for building onchain apps (dapps) that are compatible with Base, but missing or not listed within our documentation, and add it to the appropriate section / category.

_Source code for the Base Developer Docs site can be found under [/apps/base-docs](https://github.com/base-org/web/tree/master/apps/base-docs). The documentation site is built using [Docusaurus](https://docusaurus.io/)._

**Comment by ptdatta** [comment]
@taycaldwell Can I give it a try?
