### ISSUE TITLE
[Onchain Squad] Address any bugs / typos within Base Camp

### ISSUE THREAD

**Issue by taycaldwell** [base-org/web#254]
### Context

We have our own educational curriculum for becoming a full-fledge blockchain dev and Base builder known as Base Camp!

### Ask

Read through the Base Camp content, and if you come across any bugs, typos, mistakes, broken links, etc. please create a pull request (PR) with a fix. (We'll also consider general improvements to the content itself.)

_Source code for the Base Camp can be found under [/apps/base-docs/base-camp](https://github.com/base-org/web/tree/master/apps/base-docs/base-camp). The site is built alongside the developer documentation and uses [Docusaurus](https://docusaurus.io/)._

**Comment by hoysal08** [comment]
@taycaldwell  fixed one basic issue , its a broken link live on official docs.
https://github.com/base-org/web/pull/271

**Comment by taycaldwell** [comment]
Closing issue with conclusion of 30 Days of Web3.
