### ISSUE TITLE
Bug: Code boxes are not using correct monospace font

### ISSUE THREAD

**Issue by briandoyle81CB** [base-org/web#259]
### Describe the bug

Code boxes are not using correct monospace font

### Steps

It's easies to see on pages that have a text table in a code box:  https://docs.base.org/hardhat-tools-and-testing/hardhat-profiling-gas/

Here, the lack of monospace font breaks the table formatting because periods and dashes take up vastly different widths.  

It's present in all code boxes, which makes them look subtly sloppy.

### Expected behavior

Code boxes should use Coinbase Sans monospace

**Comment by ptdatta** [comment]
Hey @briandoyle81CB Can I give it a try?

**Comment by briandoyle81CB** [comment]
@ptdatta Someone got this one done already, but we're very happy to take PRs!  Talk to us first before you take on something huge, so we can make sure you don't go down the wrong path, but for smaller items like this one, you can just do a PR!  Thanks for being interested in helping!

**Comment by ptdatta** [comment]
@briandoyle81CB Thanks for responding. Yes, I am starting with the small ones and gradually understanding the project and going towards the bigger ones. Thanks for the clarification.
