### ISSUE TITLE
Support bridging custom tokens by contract addresses

### ISSUE THREAD

**Issue by chicken-juju** [base-org/web#282]
### Describe the solution you'd like

Since you are not bulk-whitelisting tokens from the [unified token list](https://github.com/ethereum-optimism/ethereum-optimism.github.io), the bridge page should allow bridging custom tokens by entering their addresses. [Optimism bridge](https://app.optimism.io/bridge/withdraw) does this.

Projects are being forced to deploy their [forked bridge UI](https://github.com/base-org/web/pull/101) or use 3rd party bridges.

![image](https://github.com/base-org/web/assets/121341106/06478a82-a6b8-405e-a6af-6773d8a1d858)

**Comment by wbnns** [comment]
@chicken-juju 

Thanks for taking the time to open this issue! We've added this to our backlog, pending to be reviewed.

**Comment by wbnns** [comment]
Hello, since this official bridge has been deprecated, this issue would no longer be possible to remediate
