### ISSUE TITLE
Docs Request: Correction Needed for Complex Onchain NFTs Guide Link in Minting an NFT in a Frame Guide

### ISSUE THREAD

**Issue by twynne20** [base-org/web#318]
### What is the issue you are encountering with the docs?

Issue Description:
The link to the Complex Onchain NFTs guide in the documentation contains a typo that could lead to confusion and hinder users from accessing the correct resource. The current link is duplicated with an extra "https://" prefix, making it non-functional.

Current Incorrect Link:
`https://https://docs.base.org/building-with-base/guides/complex-onchain-nfts`

Expected Correct Link:
`https://docs.base.org/building-with-base/guides/complex-onchain-nfts`

### Links to Impacted Docs

[nft-minting-frame.md](https://github.com/base-org/web/blob/master/apps/base-docs/docs/building-with-base/guides/nft-minting-frame.md?plain=1)

### Describe the solution you'd like to see.

Please correct the URL by removing the redundant "https://" prefix to ensure the link directs users to the intended guide without errors. This will improve the documentation's usability and accessibility, allowing developers to more easily find and utilize the Complex Onchain NFTs guide.

**Comment by briandoyle81CB** [comment]
Resolved by 319
