### ISSUE TITLE
[Onchain Squad] Docs Request: Add Keywords to Frontmatter for All Base Camp Docs

### ISSUE THREAD

**Issue by briandoyle81CB** [base-org/web#331]
### What is the issue you are encountering with the docs?

The Base Camp docs are missing the `keywords` section in the frontmatter.  This section helps search engines find the content.

This should be added one folder at a time!

### Links to Impacted Docs

https://raw.githubusercontent.com/base-org/web/master/apps/base-docs/base-camp/docs/contracts-and-basic-functions/hello-world-step-by-step.md

And every other doc under /base-camp/

### Describe the solution you'd like to see.

Add a keywords section with appropriate keywords.

Example:  https://raw.githubusercontent.com/base-org/web/master/apps/base-docs/docs/building-with-base/guides/account-abstraction-with-biconomy.md

### Additional context

**IMPORTANT:** Please check for PRs before making one for a given doc.  A PR should only contain updates for the files in a single folder of content.

We don't want to have several people trying to do all of them all at once, resulting in wasted effort!

**Comment by taycaldwell** [comment]
Closing issue with conclusion of 30 Days of Web3.
