### ISSUE TITLE
[Onchain Squad] Docs Request: Contract to Contract Exercise

### ISSUE THREAD

**Issue by briandoyle81CB** [base-org/web#332]
### What is the issue you are encountering with the docs?

**This is a very advanced issue.  Please do not start without first discussing with @briandoyle81CB!  Tag me here if you are interested, and we can discuss on Discord**

The Contract to Contract lessons are missing an exercise with a smart contract graded unit test awarding an NFT.  This exercise should match the others in terms of scope and complexity, and require the learner to demonstrate mastery of the learning objectives for this section.

It should inherit from the Cafe smart contract and contain tests written in the same format as the others.

### Links to Impacted Docs

https://docs.base.org/base-camp/docs/interfaces/contract-to-contract-interaction

### Describe the solution you'd like to see.

A focused exercise testing against the learning objectives for this section.

### Additional context

Example of a unit test: https://sepolia.basescan.org/address/0x15534ed3d1dba55148695b2ba4164f147e47a10c#code#F18#L1

**Comment by taycaldwell** [comment]
Closing issue with conclusion of 30 Days of Web3.
