### ISSUE TITLE
Docs Request: HOW TO DEPLOY SMART CONTRACT ON BASE (Newbie guide)

### ISSUE THREAD

**Issue by Rholarr29** [base-org/web#340]
### What is the issue you are encountering with the docs?

I have been trying to deploy smart contact on base but I haven’t seen a guild on how to do 

### Describe the solution you'd like to see.

I would appreciate if I guide is given as a reply to this issue

**Comment by twynne20** [comment]
Hey @Rholarr29! I would recommend checking out [Base Camp](https://docs.base.org/base-camp/docs/welcome), it's a great intro to Ethereum Development & building on Base!

Additionally, you could checkout [Base Guides - Deploying a Smart Contract](https://docs.base.org/guides/deploy-smart-contracts) where it details how to do this with Hardhat, Foundry, Remix, and other tools.

If you have any questions or issues feel free to comment here & I can support.

**Comment by briandoyle81CB** [comment]
Thanks @twynne20!  @Rholarr29, closing this issue, but feel free to reopen and add more detail if the links above don't have what you're looking for!
