### ISSUE TITLE
Bug: AI chatbot blocks navigation on mobile

### ISSUE THREAD

**Issue by mtlynch** [base-org/web#385]
### Describe the bug

AI chatbot widget blocks the "Next" link.

### Steps

1. Go to https://docs.base.org/
2. Scroll to the bottom of the page
3. Try to click the "Next" link
4. Link is unclickable due to the AI chatbot widget

### Expected behavior

The "Next" link is clickable

### Additional info

![image](https://github.com/base-org/web/assets/7783288/108a45b9-70c0-45e6-b3ab-836b2d9acfb4)

### Environment

- OS: Android
- Browser: Firefox
- Device: Pixel 7a

**Comment by razashozab44** [comment]
i cannot see the Next Option in bottom??

**Comment by wbnns** [comment]
Thanks you all, we'll get this fixed.

**Comment by wbnns** [comment]
@mtlynch @razashozab44 

Thanks for the feedback on this! Resolved in #424.
