### ISSUE TITLE
Is the bridge part reusable in another existing op stack instance?

### ISSUE THREAD

**Issue by zhiqiangxu** [base-org/web#468]
### What is the issue you are encountering with the docs?

Is the bridge part dedicated for base's own usage, or it can also support another existing op stack instance?

### Describe the solution you'd like to see.

If the bridge is also supposed to be reusable in  another existing op stack instance(which would be very helpful), I'd like to see the detailed documents.

**Comment by zhiqiangxu** [comment]
Hey @wbnns , thanks a lot for the answer, but https://docs.optimism.io/builders/app-developers/bridging/basics is for the transaction part, not for the UI part(which is exactly what this project does on top of optimism sdk).

Is there any document on how one can use this project for private deployed instance of OP stack?

**Comment by wbnns** [comment]
@zhiqiangxu Thanks for the context and apologies for the delayed reply. I unfortunately do not have any documentation WRT setting up the bridge interface frontend. :/ Sorry I can't be more helpful here!
