### ISSUE TITLE
Bug: Stuck on base bridge

### ISSUE THREAD

**Issue by linkeong88** [base-org/web#485]
### Describe the bug

After bridging token is not arriving on base

### Steps

1) Go to base bridge contract ( https://etherscan.io/address/0x3154cf16ccdb4c6d922629664174b904d80f2c35#writeProxyContract#F2) 

2) try to bridge token
3)Token doesn’t arrive on base network
4) Relay message fails on base network

### Expected behavior

Expected if token is not available on base to either mint a custom token or to revert the token back to main net or to allow to bridge back

### Additional info

I have send a bridge from ethereum main net to base chain using the contract bridgeerc20to, however when it arrived on base it shows FailedRelayedMessage but does not proceed further. Now I have a stuck bridge and I’m unable to go forward and unable to revert. What is the handling for this error? I see previously if the message failed it gets reverted back to main net

https://etherscan.io/tx/0x14c77dc75bf19e5eba3c6c5a853ad34430368f0746b4589d3ebfbbc57b8147b7

https://basescan.org/tx/0x3e2ec42e03d20aa8c3c06a38f1b55a502078dcaa80e5113936387eab47c90f28#eventlog

**Comment by wbnns** [comment]
@linkeong88

Hi there! As the bridge has been deprecated, would highly recommend using https://superbridge.app/base or https://brid.gg/ for assistance with completing your transaction -- these sites are built on top of the Base protocol using the same contracts as bridge.base.org and their support teams can help you complete your transaction if you're still experiencing an issue.
