### ISSUE TITLE
Use @eth-optimism/tokenlist for asset list

### ISSUE THREAD

**Issue by belbix** [base-org/web#70]
### Is your feature request related to a problem? Please describe.

You described that you are using the token list from @eth-optimism/tokenlist in your docs https://github.com/base-org/web/blob/3d946cc9d0f24341da5304ec84e7a46f9bebb59b/apps/base-docs/docs/tokens.md?plain=1#L26

However, you have just dedicated [assets.ts ](https://github.com/base-org/web/blob/3d946cc9d0f24341da5304ec84e7a46f9bebb59b/apps/bridge/assets.ts) and no clue how to add a token to them.

### Describe the solution you'd like

Please update it manually or change to automatically usage the token list from the optimism repo.

**Comment by wbnns** [comment]
@belbix 

Hi there! Thanks for raising this issue. Yes, this is for allowlisted asset to be on bridge.base.org, whereas the Superchain Token List (STL) is a mapping for all assets on the network. Not all assets on Base will be on bridge.base.org, as it's a separate review and listing process.

That said, if you have an asset, putting it on the STL is the most important step to potentially getting on bridge.base.org in the future, as that's where the team reviews and pulls from.

Hope that helps! If you have any questions or if there's anything else we can do to help, please don't hesitate to let us know.

I will open a PR suggesting we add an in-line comment in this file to make this more clear.

**Comment by belbix** [comment]
@wbnns 
Thanks for your reply!
I'm a founder of tetu.io and we are launching on Base in upcoming weeks.
We will need to move a significant amount of TETU tokens on Base chain and for security reasons, of course, prefer the native bridge.
How can we be whitelisted in your token list?

PR on optimism https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/536
DeFillama page https://defillama.com/protocol/tetu

**Comment by wbnns** [comment]
@belbix 

Thanks for following up! Inclusion on bridge.base.org is a separate review process. Unlike the STL, not all assets are included but I can see from #101 you have requested this.

Our team will review and follow-up there with status updates or requests for further information.

**Comment by chicken-juju** [comment]
A lot of projects made PRs to the [unified token list](https://github.com/ethereum-optimism/ethereum-optimism.github.io) but did not make it to your bridge page. A middle path should be the ability to bridge custom tokens by entering address, similar to what [Optimism bridge](https://app.optimism.io/bridge/deposit) does. Projects are being forced to deploy their own forks.

**Comment by zencephalon** [comment]
@chicken-juju good idea!
