### ISSUE TITLE
Bug: TOC missing 1st topic and duplicates last topic

### ISSUE THREAD

**Issue by gin** [base-org/web#986]
### Describe the bug

TOC missing 1st topic and duplicates last topic

### Steps

1. Go to https://docs.base.org/base-learn/docs/frontend-setup/building-an-onchain-app/
(or other base-learn and tutorial pages)

### Expected behavior

Expect TOC not to have missing 1st topic
Expect TOC not to have duplicated last topic 

![Screenshot 2024-09-08 at 2 29 29 PM](https://github.com/user-attachments/assets/ee0d6d12-62f4-4192-8018-4319fe49cd88)

### Additional info

However, when building repository locally, this issues does not appear.
Built locally with:
```
yarn workspace @app/base-docs dev
```

### Environment

OS: macOS
Browsers: Chrome, Brave, Firefox, Safari

**Comment by davidstrouk** [comment]
It seems like this has been solved. It appears as intended for me

<img width="1511" alt="Screenshot 2024-10-27 at 21 41 48" src="https://github.com/user-attachments/assets/dcfc949d-4f06-4634-9095-6c67bb0e402a">

**Comment by wbnns** [comment]
Indeed, confirming this is resolved. Thanks you all.
